language: python

language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
#  - "pypy3" # Pypy3 2.4.0
# command to install dependencies
install:
  - pip install -Ur test_requirements.txt
  - pip install .
# command to run tests
script:
  - pytest
  - flake8
after_success:
  - codecov
